### ISSUE TITLE
special functions meta issue

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#11579]
When fixing Sage's interface to SymPy the following special functions were missing in SymPy:

- [ ] airy_ai_general*
- [ ] airy_bi_general*
- [ ] struve_H
- [ ] struve_L
- [ ] spherical_hankel1
- [ ] spherical_hankel2
- [ ] hypergeometric_M
- [ ] hypergeometric_U
- [ ] Jacobi
- [ ] InverseJacobi
- [ ] JacobiAmplitude
- [ ] prime_pi(symbolic)
- [ ] elliptic_eu
- [ ] zetaderiv*
- [ ] dickman_rho

*The 3 derivative functions above could be emulated in Sage via SymPy diff(...) but you might want to have them explicitly.
