### ISSUE TITLE
Improvements to Rubi

### ISSUE THREAD

**Issue by certik** [sympy/sympy#13243]
Here are some of the issues with the current Rubi integrator in master:

* [ ] Rubi module is not tested in master (#13242)
* [ ] Rubi tests hang in master (#13239)
* [ ] `rubi_integrate` is 7.6x slower than `integrate` (#13240)
* [ ] `rubi_integrate` takes over 2 min to import (#13241)

**Comment by Upabjojr** [comment]
> rubi_integrate takes over 2 min to import

I guess you are loading the algebraic rules only. When I loaded all rules it took more than one hour.

**Comment by certik** [comment]
@parsoyaarihant, thanks a lot for quickly fixing most of these issues! It seems that now the most pressing is #13241, as every time I want to test something, I have to wait 2 minutes. 

Let's discuss it in #13241, so I moved @Upabjojr's comment here: https://github.com/sympy/sympy/issues/13241#issuecomment-326746212

**Comment by rwst** [comment]
Note that Rubi 4.10 from Jan 2017 has been replaced with Rubi 4.14 from March 2018 on their website. I can't say for sure but I think the number of rules has visibly increased. Unfortunately the package has no release notes.

**Comment by Upabjojr** [comment]
@rwst the number of rules is not a problem, as we have a code generator. The increased number of utility functions, on the other hand, requires some more work.

**Comment by rwst** [comment]
Also, ruleset 1.2/1.3/1.4 have become 1.1.2/1.1.3... etc, so the numbering of your testfiles does no longer correspond.

**Comment by rwst** [comment]
There may be a way to implement Rubi differently. TLDR: putting it in fixed code but not manually but automatically. I'm speculating here. Instead of having a database with entries `input pattern: result` and a program that matches the start expression against all input patterns; then the result (if it contains an integral) again against all input patterns etc. pp. a preparation step would match all resulting integrals in the database against all input patterns and generate code with the resp. calls immediately, so that after starting SymPy only the generated code is run without any pattern matching except the very first (the original expression).

As I understand it is now, the first matching finds a rule, produces a result, and if the result contains an integral, the integral expression is matched again. The problem is that results can contain several integrals and this means several matchings per call level. Simple expressions thus already may need up to about ten integral matchings because of the rule interdependencies.

**Comment by rwst** [comment]
Generally I think that, already in Rubi section 1.1 (plus dependencies in other section parts), the interdependencies are so intricate that small inaccuracies in matching can lead to loops. Section 1.1 is therefore a good testing ground for a matcher that tries to emulate Mathematica's matcher.
