### ISSUE TITLE
Improve simplification

### ISSUE THREAD

**Issue by ylemkimon** [sympy/sympy#13288]
**simplify() :**
- [x] ~fix factor() of expression with float coefficients: 7 issues [#13198]~
- [x] call cancel again: #10347 [#13264]
- [x] add rationalize flag [#13264]
- [ ] add LambertW function simplification: #5080
- [ ] add `extension=True` to polynomial operations like `cancel()`: #11500, #5428
Polynomial operations on algebraic number domain is slow and causes many errors like NotAlgebraic, ZeroDivisionError, NotImplementedError, etc. Maybe like:
```python
try:
    cancel(expr, extension=True)
except Exception:
    cancel(expr)
```
- [ ] add `powdenest()` to simplify `exp(y*log(x))` as `x**y`: #5103
Breaks following:
```python
eq3 = x*exp(f(x)/x) + f(x) - x*f(x).diff(x)
sol3 = Eq(f(x), log(log(C1/x)**(-x)))
assert checkodesol(eq3, sol3, order=1, solve_for_func=False)[0]
```
- [ ] add `expand_complex()` or `as_real_imag()`: #7569, #10403
- [x] simplify by rewriting expression: #11988 [#13113]
However, `simplify()` is expensive function and it calls it N times.

**powsimp():**
- [x] fix ValueError when base is float and Pow is argument of Mul: #9183 [#13131]
- [x] fix nan when either numerator or denominator of base is 1 and exp is infinite: #10095 [#13131]
- [x] fix KeyError when one base is Float and another is equal Rational(Integer) [#13131]
- [ ] k**oo to zero where k is in (-1, 1): #10095 (comment)

**combsimp():**
- [x] binomial simplifcation: 5 issues [#13210]
- [x] separate gammasimp from combsimp: #9785 [#13210]
- [x] expand gamma functions with rational number argument: #6153, #10101 [#13210]

**trigsimp() and exptrigsimp():**
- [x] improve detection of hyperbolic functions: #10124 [#13265]
- [x] fix NotImplementedError with sech or csch [#13259]
- [x] fix incorrect application of TR10i with hyper_as_trig: #11685 [#13259]
- [ ] integrate exptrigsimp into trigsimp(or change the order of them in `simplify()`): #8758

**Legend:**
issue: issue # [PR #]
✓ : PRed
~Strikethrough~ : Merged or fixed

**Comment by gutow** [comment]
Idea for efficiency improvement (speedup) of simplifying expressions where things cancel out. #19525
