### ISSUE TITLE
Functions that require support in the MathML presentation printer

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16036]
The following functions/classes are currently not supported in the MathML presentation printer. Where applicable there is a LaTeX rendering of the expected output, possibly correct MathML code (note the different tags for numbers and named variables etc, which must be considered in the implementation) and maybe some more information. Note that the MathML printer will print __something__, typically the name of the function/class, but this is not the expected output.

This list will be updated.

## Functions/Classes
 - [ ] Tuple: `Tuple(1, 2)`
![image](https://user-images.githubusercontent.com/8114497/53200677-6ef74e80-3622-11e9-8900-5909d9453236.png)
Currently this gives ` <mrow><mi>tuple</mi><mfenced><mn>1</mn><mn>2</mn></mfenced></mrow>` (from the general function printer) where basically the first `<mi>tuple</mi>` should be removed to get the correct rendering.

 - [ ] ImageSet: 

  - [ ] ConditionSet: see #15353 (no error, but to see how it should be printed)

  - [ ] FiniteSet: see #15353 (no error, but to see how it should be printed)

  - [ ] SeqFormula: see #12629 `SeqFormula(a, (a, 0, x))` should be 
![image](https://user-images.githubusercontent.com/8114497/53201318-fabdaa80-3623-11e9-8acc-83bb22210bc9.png)
Correct MathML code `<msubsup><mfenced open="{" close="}"><mi>a</mi></mfenced><mrow><mi>a</mi><mo>=</mo><mn>0</mn></mrow><mi>x</mi></msubsup>`

 - [ ] lerchphi: see #6013, capital phi: `<mi>&#x3A6;</mi>`

 - [ ] polylog: see #6013 `polylog(s,z)` should give
![image](https://user-images.githubusercontent.com/8114497/53201449-525c1600-3624-11e9-998d-f99c1de1d6d7.png)
Correct MathML code: `<msub><mi>Li</mi><mi>s</mi></msub><mfenced><mi>z</mi></mfenced>`

 - [ ] Integers: `<mi mathvariant="normal">&#x2124;</mi>`
 - [ ] Complexes: `<mi mathvariant="normal">&#x2102;</mi>`
 - [ ] Naturals: `<mi mathvariant="normal">&#x2115;</mi>`
 - [ ] Reals:  `<mi mathvariant="normal">&#x211D;</mi>`
 - [ ] Naturals0: `<msub><mi mathvariant="normal">&#x2115;</mi><mn>0</mn></msub>`
- [ ] Union: `<mo>&#x222A;</mo>`
- [ ] Intersection: `<mo>&#x2229;</mo>`
 - [ ] Complement: `<mo>&#x2216;</mo>`
- [ ] EmptySet: `<mo>&#x2205;</mo>`
- [ ] Interval: `<mfenced open="("/"[" close=")"/"]"><mi>start</mi><mi>stop</mi></mfenced>`

- [ ] And: `<mo>&#x2227;</mo>`
- [ ] Or: `<mo>&#x2228;</mo>`
 - [ ] Not: `<mo>&#xAC;</mo>`

## Resources

Presentation MathML reference: https://www.w3.org/TR/MathML2/chapter3.html

See how things render: https://www.tutorialspoint.com/online_mathml_editor.php

Latex <-> Equation editor <-> MathML: http://www.wiris.com/editor/demo/en/developers

**Comment by shubhamabhang77** [comment]
Hey can you tell me more about this . I would like to work on this as there are some unmarked checkboxes.

**Comment by oscargus** [comment]
Basically what I've done is to look at the LaTeX output and tried to mimic that with MathML. Often one can more or less just copy the corresponding LaTeX printer method and change it line by line.

For example, 
https://github.com/sympy/sympy/blob/a0711ebd8d1b58ce0930a882c2cff09e6678cb08/sympy/printing/latex.py#L1906-L1907
should be something like
```
mrow = ...('mrow')
mrow....  self._print(a.args[0])
mo = ... ('mo')
mo....  self._print(...'&#x2208;')
mrow... (mo)
mrow....  self._print(a.args[1])
return mrow
```

Others require a bit more thinking, but still the LaTeX printer code is a good source to how it should look. There are online tools to convert LaTeX equations to visuals if you are not using a Python console that does it or know LaTeX. Just run the `latex` command in Sympy to get the corresponding LaTeX code and paste it into e.g. http://latex2png.com/ to see what it should/could look like.

**Comment by oscargus** [comment]
There are tens of more functions that can be added as well (one can simply compare the LaTeX printer and MathML printer and see which methods are missing), but these are somehow the once I have currently identified.

**Comment by oscargus** [comment]
Some examples of special functions for comparison:
![image](https://user-images.githubusercontent.com/8114497/53474810-7083a500-3a6e-11e9-95ae-21499d7637b6.png)

**Comment by oscargus** [comment]
Some more functions:
![image](https://user-images.githubusercontent.com/8114497/53475334-fbb16a80-3a6f-11e9-8cf5-d6c7ba839af8.png)

**Comment by oscargus** [comment]
This may be a bit confusing since the "Expression" column is printed with `str`. Hence, to sort out the printing of `true` (which prints as `True`), the method `_print_booleantrue` should be defined etc.

**Comment by shubhamabhang77** [comment]
Yeah I would like to work on some functions. I am not able to figure out how the mathml code should be. Tell me some examples so that I can get an idea.

**Comment by shubhamabhang77** [comment]
We have to print the same symbols in mathml as they are printed in latex, right? For e.g. zeta(x) should be printed same as printed in latex.

**Comment by shubhamabhang77** [comment]
I have tried this with Lambda, see if this code is correct.
```
    def _print_Lambda(self, e):
        x = self.dom.createElement('mo')
        x.appendChild(self.dom.createTextnode('&#x21A6;'))
        return x
```

**Comment by oscargus** [comment]
The explanation was not so good for Lambda. The symbol is the arrow used. There are more things that must be printed.

I think zeta etc can be easily solved in the mathml_tag dictionary. I actually just about to try it out in another PR (for all functions above which is replaced by a single character).

**Comment by oscargus** [comment]
@shubhamabhang77 Look at this for how Lambda should be printed (the LaTeX column):
![image](https://user-images.githubusercontent.com/8114497/53521618-e9b7e200-3ad8-11e9-8e4d-faadbbf9f634.png)

Tuple is added in #16065 which is still to be merged (although I think that will happen quite soon).

**Comment by shubhamabhang77** [comment]
Suppose ```Lambda(x, x+1)``` is the expression , then how can one access the arguments which are in bracket i.e. ```x``` and ```x+1``` ?

**Comment by shubhamabhang77** [comment]
Should it look like this? 
```
    def _print_Lambda(self, e):
        mrow = self.dom.createElement('mrow')
        x = self.dom.createElement('mfenced')
        x.appendChild(self._print(e.args[0]))
        x.appendChild(self.dom.createTextnode('&#x21A6;'))
        x.appendChild(self._print(e.args[1]))
        mrow.appendChild(x)
        return mrow 
```

**Comment by oscargus** [comment]
Yes, that should most likely work.

**Comment by shubhamabhang77** [comment]
I have implemented some functions.

**Comment by shubhamabhang77** [comment]
I am getting some error while implementing floor and ceiling.
```
    def _print_floor(self, e):
        mrow =  self.dom.createElement('mrow')
        x = self.dom.createElement('mfenced')
        x.setAttribute('open', '&#x230A;')
        x.setAttribute('close', '&#x230B;')
        for arg in e.args:
            x.appendChild(self._print(arg))
        mrow.appendChild(x)
        return mrow 
```
but when I try some example
I get this.
```
In [1]: w = floor(x)                                                                                                                                                                                               

In [2]: print_mathml(w, printer='presentation')                                                                                                                                                                    
shubham floor
<mrow>
	<mfenced close="#x230B;" open="#x230A;">
		<mi>x</mi>
	</mfenced>
</mrow
```
do you why this happens?

**Comment by shubhamabhang77** [comment]
I am getting some error while implementing floor and ceiling.
```
    def _print_floor(self, e):
        mrow =  self.dom.createElement('mrow')
        x = self.dom.createElement('mfenced')
        x.setAttribute('open', '&#x230A;')
        x.setAttribute('close', '&#x230B;')
        for arg in e.args:
            x.appendChild(self._print(arg))
        mrow.appendChild(x)
        return mrow 
```
but when I try some example
I get this ```&amp;``` extra.
```
In [1]: w = floor(x)                                                                                                                                                                                               

In [2]: print_mathml(w, printer='presentation')                                                                                                                                                                    
shubham floor
<mrow>
	<mfenced close="&amp;#x230B;" open="&amp;#x230A;">
		<mi>x</mi>
	</mfenced>
</mrow
```
do you why this happens?
This is the case for ceiling as well.

**Comment by oscargus** [comment]
I've also got that. The only way I have figured out is to add the Unicode character in the code. This will be translated to the correct code once printed.

Look at https://www.tutorialspoint.com/mathml/mathml_algebra.htm and copy the symbol from the left-most column.

**Comment by oscargus** [comment]
Or maybe better is to use `u"\u2309"` etc as that does not require that the file is saved using Unicode.

**Comment by oscargus** [comment]
@shubhamabhang77 feel free to "assign" some functions for you to work on. No problems if you unassign them later. Better that than we work on the same functions.

**Comment by shubhamabhang77** [comment]
I have made a PR. Take a look at it.
