### ISSUE TITLE
Discussion regarding the API for control package

### ISSUE THREAD

**Issue by namannimmo10** [sympy/sympy#18460]
Hello everyone,

Before this, some contributors made efforts to add `control` package to `sympy.physics` [here](https://github.com/sympy/sympy/pull/9916) and [here](https://github.com/sympy/sympy/pull/17866). 

There is a great python library for the operations of control systems. 
https://python-control.readthedocs.io/en/latest/index.html
But I want sympy to have a symbolic version of that. 

A basic overview of what needs to be added can be found [here](https://github.com/sympy/sympy/pull/9916#issue-44919344). But I think some more operations can also be added to enhance the toolbox. Like given in this link: https://www.wolframalpha.com/examples/science-and-technology/engineering/control-systems/
  
I have already raised a [Pull request](https://github.com/sympy/sympy/pull/18436) for adding such toolbox and this can be done in these 5 steps:
- [ ] Discussion regarding the API and what operations can be added.
- [ ] Addressing all the comments mentioned in #17866 and #9916
- [ ] Discussing class design and prototypes.
- [ ] Final implementation along with unit tests.
- [ ] Adding Documentation for all the classes/functions.

Any advice from the community would be really appreciated.

**Comment by Chanakya-Ekbote** [comment]
I totally agree. In addition to that, we could have a combined control system, as well as a signal processing package as both applications, go hand in hand (to a certain extent). 

I had raised a PR to try and include magnitude response, phase responses, magnitude plots as well as phase plots, finding out the poles and zeros of an equation as well as pole-zero plots. The link to the PR can be found here [PR #18419: https://github.com/sympy/sympy/pull/18419.]. I think this could be added to the control package. 

I also wanted to add some other features that could help in the signal processing domain as well as the control system domain. I have elaborated my ideas in this discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sympy/K5i87mX8Dwo/nOB-iVvREgAJ.

**Comment by namannimmo10** [comment]
I agree that these disciplines overlap to a certain extent. But it's just that they are separated by a set of common tools.

**Comment by Chanakya-Ekbote** [comment]
ping @oscarbenjamin @moorepants @jksuom

**Comment by sylee957** [comment]
In my opinion, `TransferFunctionModel` and `StateSpaceModel` can subclass `Basic` and can be sympifyable.
I can say that they are quite well-defined symbolic models used in conventional softwares like Mathematica. Of course, I don't say that every objects should be sympifyable, but things can be complicated later if it does not follow the sympy standard design patterns and later if you are trying to add something like symbolic representations of interconnecting the modules.

**Comment by namannimmo10** [comment]
Wouldn't it be better if we write this module as a set of few functions?
 > In my opinion, TransferFunctionModel and StateSpaceModel can subclass Basic

Maybe that is better if we're trying to use other sympy methods such as `subs` etc..

**Comment by sylee957** [comment]
It can be different if it is rewritten as a set of functions, than writing to Basic would not be an issue for a while

But if anything new is going to be implemented as a class and that wraps around sympy types, then it's better to be inheriting `Basic` from the first place. For example, there were obvious needs of `subs`, `_repr_latex_` and they had to be redefined in any way for these models.

**Comment by namannimmo10** [comment]
Alright, `TransferFunctionModel` and `StateSpaceModel` will subclass `Basic`. 

Regarding the API for `StateSpaceModel`,
I think it would be better if we do [this](https://github.com/sympy/sympy/pull/9916#discussion_r39408652)... Like the way it is implemented [here](https://github.com/python-control/python-control/blob/66bee9d31c0e4913aa2bda614794845563a616d6/control/statesp.py#L124). What do you think?

**Comment by sylee957** [comment]
What kind of features do you think that StateSpaceModel is lacking for python-control?

I think that most of the stuff already mirrors python-control.

**Comment by namannimmo10** [comment]
This would be a **symbolic version** of linear control systems. I guess that would be one of the reasons.. 
Most of the things mentioned in  Appendix A of [this thesis](https://www.mcs.anl.gov/~wozniak/papers/wozniak_mmath.pdf) (mentioned in GSoC ideas list) are there in python-control..

**Comment by namannimmo10** [comment]
>  if you are trying to add something like symbolic representations of interconnecting the modules.

We can also do that if everyone suggests.

**Comment by sylee957** [comment]
`StateSpaceModel` already uses sympy matrix, so it would still be able to support most of the symbolics.

However, there can be some differences of enabling symbolics partially in computation, or making the whole model symbolic.
Do you mean that it should be implemented as the latter way?

**Comment by namannimmo10** [comment]
> or making the whole model symbolic.

I don't know how difficult that would turn out to be. Please refer [this comment](https://github.com/sympy/sympy/pull/17866#issuecomment-552115713). 
But if that's what is required to differentiate it from python-control, then I'm willing to move forward..... 
But for that, I need some guidance.

**Comment by sylee957** [comment]
Often, `Basic` offers safe immutable design patterns and can resolve lots of issues regarding rewriting, printing, picklingor such that and I think that this is one of the reasons that most of the stuff should be implemented as `Basic` possible.

I think that converting the objects to the form that are compatible with `Basic` is simple.

1. I'd first try to define the constructor with `__new__` than `__init__`, such that it sympifies the arguments and

   - `StateSpaceModel` uses `Basic.__new__(cls, A, B, C, D)` signature where `A, B, C, D` are matrices.
   - `TransferFunctionModel` uses `Basic.__new__(cls, num, denom)` signature where `num`, `denom` are polynomials. that 

   `represent`, `block_represent` should be derived from the `.args`, rather than storing the `represent`, `block_represent` by mutating the objects.

2. I'd try to move `__str__`, `__repr__`, `_repr_latex_` to `_print_TransferFunctionModel` and `_print_StateSpaceModel` in `StrPrinter`, `LatexPrinter`

3. `__eq__` don't have to be defined if it inherits `Basic`.

4. I'd write `_eval_rewrite_as_TransferFunctionModel` and `_eval_rewrite_as_StateSpaceModel`. And then the model conversion can be possible by `.rewrite(StateSpaceModel)`

5. I'd not define `__getattr__` to inherit the methods from the wrapped objects, because `Matrix` can have a lot of obscure stuff. But I'd design some stuff like jordan decomposition carefully.

And I'd believe that other things would be easier.

**Comment by namannimmo10** [comment]
> And then the model conversion can be possible by .rewrite(StateSpaceModel)

That is a great idea :)

Seems like there are so many benefits while we subclass `Basic`. I'll include all this in my proposal, and I'll also try to add some other methods which are there in python-control but not in #17866
For instance -- `isObservable`,  `RootLocusPlot`, `Nyquist` and `Bode` plots and some more that can be useful for engineering point of view.

Thanks for the suggestions, @sylee957

**Comment by sylee957** [comment]
Yes, but I'd try to name `is_observable`, `root_locus_plot`, `nyquist_plot`, `bode_plot` for naming consistency.

**Comment by namannimmo10** [comment]
OK. I'll follow snake_case naming style.

**Comment by sylee957** [comment]
I'd also make anchor an additional symbol `s` in the arguments like `Basic.__new__(cls, A, B, C, D, s)` and `Basic.__new__(cls, num, denom, s)` if it can allow symbolic coefficients. (For numeric cases, `s` may not be needed like done in python-control, but for allowing symbolic coefficients, there should be a way to anchor the symbol `s` like done in mathematica.)

**Comment by moorepants** [comment]
Maybe s should be optional, i.e. `s=Symbol('s')`. The user will need to be able to access what s is in the transfer functions for certain downstream manipulations.

**Comment by sylee957** [comment]
But is it a good idea to specify `s` as `Symbol` than `Dummy`, considering the cases where `s` is not meant to be anything but coefficients.
I'm even thinking of internally using a model with anonymous symbols.

**Comment by moorepants** [comment]
I still don't understand what a Dummy is. So I don't know. But this is similar to the Beam module where you formulate polynomials in the class methods and need access to the independent variable for further analysis. @oscarbenjamin gave some nice suggestions on how to handle this in an issue somewhere. I forget where...

**Comment by moorepants** [comment]
Here: https://github.com/sympy/sympy/pull/17714 is where he proposed ideas for dealing with the implicit variable for time in the physics vector package.

**Comment by moorepants** [comment]
I just read https://docs.sympy.org/1.5.1/modules/core.html?highlight=dummy#sympy.core.symbol.Dummy and see that it is a symbol that ensures uniqueness regardless of its string base. So my question is then what advantage does this give over a symbol in this case? Why is it important to make the independent variable of the polynomial unique?

**Comment by sylee957** [comment]
It's because I'm thinking of defining the equalities between each system models not to depend on the names of the variables.
But of course, it doesn't have to be mandatory.

**Comment by moorepants** [comment]
I see. That could be valuable.

**Comment by namannimmo10** [comment]
Apart from the methods that are already there in #17866,  these are the following methods that I propose to add in the `StateSpaceModel` class. 
```
def observability_matrix(self):
      # Description can be found here: 
      # https://in.mathworks.com/help/control/ref/obsv.html#f3-209625
      # The matrix would be of np rows and n columns. 

def observable_subspace(self):
      # The observable subspace only depends on A and C.
      # And the observable subspace of lti system is equal to the image of its observability matrix.
      
      return self.observability_matrix().columnspace()

def is_observable(self):
      # Returns a Boolean whether or not the system would be observable.
      # If the observability matrix is non-singular, then the system would be observable.
      # According to theory, we can just find the determinant. 
      # If the det is 0, then the system is not observable else it is observable..
      # Or we can do by using `for` loops.

def __neg__(self):
      # Negates a state space system.
      
      return StateSpaceModel(self.args[0], self.args[1],  -self.args[2], -self.args[3])

def _eval_rewrite_as_TransferFunctionModel(self):
      # After this, model interconversion would simply be `.rewrite(TransferFunctionModel)`.

def series(self, other):
      # Returns the series interconnection of the system and another system (other).
      # The implementation in #17866 can be improved further
      # Like using `.args` instead of `.represent` and much more.     
```
I'll also update with the methods for `TransferFunctionModel` class. Please let me know if I've missed something or if I'm wrong somewhere.

**Comment by sylee957** [comment]
There are also some ideas from #12189 to grab.

**Comment by namannimmo10** [comment]
Cool. Noted!

**Comment by namannimmo10** [comment]
Also, Can anyone please let me know who would be my potential mentor for this project? So that I discuss all the things with him/her in advance.  Thanks.

**Comment by czgdp1807** [comment]
Take a look at https://github.com/sympy/sympy/pull/7977#issuecomment-585404002 as well.

**Comment by namannimmo10** [comment]
Hi everyone, 
I just started working on my GSoC application. Please look into [this](https://docs.google.com/document/d/1Sifc2injFLrdsSfG7FCN0PN3ZRrwRXCaKVFUcjME2Kg/edit) and let me know if changes are required. 
As discussed before, the project can be done in 4 phases.

**Phase 1**: Adding `StateSpaceModel` and `TransferFunctionModel` class. [These guidelines](https://github.com/sympy/sympy/issues/18460#issuecomment-580730059) will be followed so as to make the whole model symbolic. I'll address all the comments in #17866 and #9916. 

**Phase 2**: In this phase, I will implement more methods such as `observability_matrix`, `observable_subspace`, `is_observable`, `__neg__` (For `StateSpaceModel`), `__neg__` (for `TransferFunctionModel`), `_eval_rewrite_as_TransferFunctionModel`, `_eval_rewrite_as_StateSpaceModel`.  

**Phase 3**: At the starting of this phase, I'll add tests for the work done in Phase 1 and Phase 2. 
Documentation will also be added. Control package would be implemented by then. After that, I will add convenience function to `lambdify` the `StateSpaceModel`. Test for the same will also be added. 

**Phase 4**: In this phase, I will add `nyquist_plot` and `root_locus_plot` for `TransferFunction`. Finally, I'll add documentation and complete all the things that would still be unmerged by then.


@moorepants @sylee957 Please give some reviews on this. I'll add Phase 1 implementation plan in my application tomorrow. I want to start working on this project as soon as I can so as to maximize my chances of selection. 
Looking forward to hearing from you both. :)

**Comment by moorepants** [comment]
This all sounds cool. I think the Bode plot is used much more widely than the Nyquist plot, so I'd implement that before Nyquist.

**Comment by namannimmo10** [comment]
Thanks, @moorepants 
I'll add the Bode plot instead of the Nyquist plot. Even I was initially confused, but now I also think the bode plot should be implemented first.  So the `bode_plot` and `root_locus_plot`s are fine?? 
We can use SymPy's own `plotting` module to implement that.  

I think we should have plenty of examples in the docs. Because people tend to use the software more if the docs are top-notch.

**Comment by moorepants** [comment]
I think a Bode plot and root locus are two of the most popular control related plots used.

**Comment by namannimmo10** [comment]
Alright, we can add them. One is a frequency response plot and the other is a root locus plot for the transfer function.  Should I write the prototypes for all the features that I will add?

**Comment by namannimmo10** [comment]
> Should I write the prototypes for all the features that I will add?

Or just the outside APIs would suffice?

**Comment by oscarbenjamin** [comment]
I think that you should write tests for each part at the same time as implementing it. Writing tests afterwards is not usually a good idea as you will forget what needs to be tested. Writing tests at the same time helps to ensure that everything is implemented correctly.

**Comment by moorepants** [comment]
I agree with @oscarbenjamin. And a GSoC proposal that shows examples of use (like the "examples" sections in SymPy documentation) or even unit tests will provide a very clear picture of what you want to do.

**Comment by namannimmo10** [comment]
Thanks for the suggestions. I'll write tests in the last week of each phase.

**Comment by namannimmo10** [comment]
I have added Phase 1 implementation plan. Please check [this](https://docs.google.com/document/d/1Sifc2injFLrdsSfG7FCN0PN3ZRrwRXCaKVFUcjME2Kg/edit?usp=sharing) and leave comments if any changes are required.

**Comment by namannimmo10** [comment]
@moorepants We can drop `evaluate` for numeric solutions to the system, and focus only on symbolic evaluation and improving it even more. I'll update this in my application. Is there anything else that needs to be addressed or if I'm wrong somewhere as per my proposal, or should I move forward? Thanks!

**Comment by oscarbenjamin** [comment]
I think that numerical solutions can be fine if this is something that is added generally in sympy for working with ODEs i.e. https://github.com/sympy/sympy/issues/18023

**Comment by namannimmo10** [comment]
@moorepants, I have completed Phase 1, 2, and almost 4. Please review my proposal whenever you get time. I just want to make sure I'm doing it the right way. Thanks.

**Comment by namannimmo10** [comment]
@moorepants Please give your final feedback on my application. Looking forward to hearing from you.

**Comment by czgdp1807** [comment]
Can this, https://github.com/sympy/sympy/pull/18436 be closed? Or https://github.com/sympy/sympy/pull/18436 is going to be continued?
@moorepants @namannimmo10

**Comment by namannimmo10** [comment]
I want to work on a new PR. Please address [this](https://github.com/sympy/sympy/pull/17866#issuecomment-626205165) comment. If you agree, then we can close #18436

**Comment by namannimmo10** [comment]
> I want to work on a new PR

Actually, i want to copy the file from the most [recent commit](https://github.com/sympy/sympy/pull/17866/commits/6c609a0ad63de30f4ef7f2433257a5101d8aeaec) in #17866 and start from work from there in a new PR.
