### ISSUE TITLE
Enhancing consistency for evaluate and doit

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18837]
This issue is related to:  
- Issues #17280, #18764, #18787 
- PRs #18826, #18829

and possibly more.

# Issues

There are many 'evaluatable' classes across sympy, e.g. `Add`, `MatAdd`, `Derivative`, `Subs`, etc.  
The main concept is that `.doit()` method evaluates these, but there are heavy inconsistencies among them.

__1. `evaluate` option__
---
Some classes take `evaluate` option, which evaluates the result.
```python
>>> Add(x, x, evaluate=True)
2*x
>>> Add(x, x, evaluate=False)
x + x
>>> Derivative(x, x, evaluate=False)
Derivative(x, x)
>>> Derivative(x, x, evaluate=True)
1
```
Some classes do not:
```python
>>> Subs(x, x,1, evaluate=True) # expect 1
Subs(x, x, 1)
```

__2. `.doit(deep=False)` method__
---
Some classes return evaluated result if `doit(deep=False)` is passed.
```python
>>> Derivative(x,x).doit(deep=False)
1
```
Some classes do not:
```python
>>> Add(x, x, evaluate=False).doit(deep=False) # expect 2*x
x + x
```

__3. Evaluation using operator__
---
Matrices always return evaluated result when operator method (e.g. `__add__`) are used.
```python
>>> A = MatrixSymbol('A', 2,2)
>>> MatAdd(A, A)
A + A
>>> A + A
2*A
```
Core classes do not:
```python
>>> with evaluate(False):
>>>     expr1 = Add(1, 3)
>>>     expr2 = S.One + 3
>>> expr1
1 + 3
>>> expr2
1 + 3
```

# Suggestions
Every evaluatable classes should be able to take `evaluate` option, and `doit(deep=False)` should evaluate them. In other words, `self.doit(deep=False)` should return `self.func(*self.args, evaluate=True)` (more options may be passed by defining `_eval_doit` method).  

Evaluation design of matrix module seems good. It will be better to make core classes follow its design:
1. Prefer `evaluate=False` when classes are used.
```python
>>> Add(x, x)
x + x
>>> Add(x, x, evaluate=True)
2*x
>>> with evaluate(True):
>>>     print(Add(x, x))
2*x
```

2. Always evaluate the result when operators are used
```python
>>> x + x
2*x
>>> with evaluate(False):
>>>     print(x + x)
2*x
```

After every classes are made sure to take `evaluate` option, we can make every classes inherit `doit` from `Basic` and clean up the rest. This will make it easy to add such features:
```python
>>> d1, d2 = Derivative(x, x), Derivative(x**2, x)
>>> expr = Add(d1, d2, evaluate=False)
>>> expr
Derivative(x, x) + Derivative(x**2, x)
>>>expr.doit(properties = [lambda x: isinstance(x, Derivative)])
1 + 2*x
```

# Task lists
__Adding `evaluate` to classes__

- [x] Add `evaluate` to matrix classes (Done by #18765)
- [ ] Add `evaluate` to `Subs`
- [ ] Add `evaluate` to other classes (will be updated)

__Enable `doit(deep=False)` to return evaluated result__

- [ ] Modify `AssocOp.doit`
- [ ] (will be updated)

__Make using operator always return evaluated result__
- [ ] Modify `Expr.__add__`, `Expr.__mul__`, etc
- [ ] Modify `Number.__add__`, `Number.__mul__`, etc
- [ ] (will be updated)

__Enhance `doit`__
- [ ] Make every classes inherit `Basic.doit`
- [ ] Enable selective evaluation using `doit`

__Make core prefer unevaluated result__
- [ ] Change every '`obj.func(*obj.args)`' syntaxes used in sympy to specify `evaluate` option
- [ ] Make `global_parameters.evaluate` to be `False` by default

**Comment by namannimmo10** [comment]
I'm working on adding `evaluate` to `Subs`.

**Comment by mcpl-sympy** [comment]
@namannimmo10 
That's great. May I ask you one more?  
Currently, evaluation of `Subs` is defined in `doit` method. Can you move it to another method, make `__new__(cls, [...], evaluate=True)` call it, and finally, make `self.doit(deep=False)` return `self.func(*self.args, evaluate=True)`?

**Comment by namannimmo10** [comment]
Alright,  I'll send a PR soon!

**Comment by asmeurer** [comment]
I was going to open an issue for this but I found this one. I agree that `doit` ought to use an `_eval_doit` method. It will have to be done in a backwards compatible way with the existing classes that define `doit` instead. I'm not sure if that's doable since existing `doit` methods won't call `_eval_doit`. Perhaps we would need to deprecate redefining `doit()`.

I don't know if this was mentioned, but importantly, `_eval_doit` should not recursively call `doit`. Instead, the top-level `doit` should handle that (similar to how `expand` works).
