### ISSUE TITLE
Extending and using DomainMatrix

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20987]
This issue is to track extending the DomainMatrix code and making use of it more widely to speed up slow matrix computations. The DomainMatrix class has been introduced and extended already in a number of PRs (#18844, #19882, #20461, #20759, #20780).

## TODO

- [ ] Add docs for `DomainMatrix`
- [ ] Make `ImmutableMatrix` use `DomainMatrix` internally if all elements are integer/rational.
- [ ] Make `Matrix.charpoly` use `DomainMatrix`
- [ ] Make `Matrix.jordan_form` use `DomainMatrix`
- [ ] Make `Matrix.rref` use `DomainMatrix`
- [ ] (Other Matrix methods that could be made faster...)
- [ ] Add `DomainMatrix.__getitem__` for slicing and element access.
- [ ] (Other `DomainMatrix` utility methods to be added...)
- [ ] Add mechanism for deciding between dense and sparse representation
- [ ] Add a `DomainScalar` type
- [ ] Implement the Bareiss algorithm for `DomainMatrix.det`
- [ ] (Other fraction-free algorithms)
- [ ] Paterson-Stockmeyer method for inverse
- [ ] Solving systems of equations with charpoly
- [ ] Make `heurisch/solve_lin_sys` more efficient for sparse systems by not converting to dense
- [ ] Make `risch` use `DomainMatrix`
- [ ] Rebuild `PolyMatrix` on top of `DomainMatrix`.

## Introduction

The idea of DomainMatrix is that each matrix has an associated "domain" which is analogous to numpy arrays which have an associated "dtype". In the case of numpy arrays the dtype is e.g. `int32` or `float64` etc. With DomainMatrix each matrix has a domain such as `ZZ` (the integers)  or `QQ<sqrt(2)>` the number field `QQ(sqrt(2))` consisting of numbers of the form `a*sqrt(2) + b` where `a` and `b` are rational numbers. The domain system is explained in more detail here:
https://docs.sympy.org/dev/modules/polys/domainsintro.html

Whereas the current sympy Matrix class uses Expr instances as the elements of the matrix the DomainMatrix class uses "domain elements" for its internal representation. This makes DomainMatrix faster for many common operations (much faster in many cases) but also means that it is not entirely compatible with Matrix. It isn't simply possible to make Matrix use DomainMatrix as its internal representation because that would not be backwards compatible. It would be good to build a new Matrix class that uses DomainMatrix internally but for compatibility it would need to be a separate class from the existing Matrix class and users would need to understand that it should be used in a different way.

The easiest way to create a DomainMatrix is from the existing Matrix class like this:
```python
In [1]: from sympy.polys.matrices import DomainMatrix

In [2]: M = randMatrix(5)

In [3]: dM = DomainMatrix.from_Matrix(M)

In [4]: M
Out[4]: 
⎡65  41  80  0   88⎤
⎢                  ⎥
⎢39  60  10  28  77⎥
⎢                  ⎥
⎢42  3   10  18  54⎥
⎢                  ⎥
⎢18  54  38  54  76⎥
⎢                  ⎥
⎣52  64  55  37  28⎦

In [5]: dM
Out[5]: DomainMatrix([[65, 41, 80, 0, 88], [39, 60, 10, 28, 77], [42, 3, 10, 18, 54], [18, 54, 38, 54, 76], [52, 64, 55, 37, 28]], (5, 5), ZZ)
```
From there we can time basic operations like matrix multiplication:
```python
In [6]: %time ok = M**10
CPU times: user 104 ms, sys: 11.8 ms, total: 116 ms
Wall time: 137 ms

In [7]: %time ok = dM**10
CPU times: user 644 µs, sys: 1 µs, total: 645 µs
Wall time: 651 µs
```
This shows that even something as basic as matrix multiplication for a matrix of integers can be a lot faster (200x here) if DomainMatrix is used instead of Matrix. It also shows just how slow the current Matrix class is: there is a lot of room for improvement in terms of speed. It's important to know that many operations with Expr are cached so computing the same matrix power again will be faster:
```python
In [13]: %time ok = M**10
CPU times: user 2.21 ms, sys: 62 µs, total: 2.28 ms
Wall time: 2.35 ms
```
That shows that even once all of the intermediate calculations are cached Matrix is still slower than DomainMatrix (which does not use any caching).

Matrix multiplication with integer elements is one of the least interesting calculations to show the speed up of `DomainMatrix`. More interesting domains show a bigger difference and many other operations can be extremely slow with Matrix:
```python
In [58]: M = randMatrix(6, 6) + randMatrix(6, 6) * I

In [59]: dM = DomainMatrix.from_Matrix(M)

In [60]: %time ok = dM.charpoly()
CPU times: user 19.8 ms, sys: 266 µs, total: 20.1 ms
Wall time: 20.3 ms

In [61]: %time ok = M.charpoly()
CPU times: user 2min 2s, sys: 394 ms, total: 2min 2s
Wall time: 2min 3s
```
This operation takes 20 milliseconds for `DomainMatrix` but 2 minutes for `Matrix`. That's a 6000x speed difference! The matrix in question isn't even that big or complicated:
```python
In [63]: M
Out[63]: 
⎡88 + 83⋅ⅈ  89 + 79⋅ⅈ  84 + 77⋅ⅈ  42 + 13⋅ⅈ  39 + 59⋅ⅈ  11 + 35⋅ⅈ⎤
⎢                                                                ⎥
⎢96 + 56⋅ⅈ  42 + 37⋅ⅈ  27 + 52⋅ⅈ  77 + 89⋅ⅈ  56 + 47⋅ⅈ  16 + 54⋅ⅈ⎥
⎢                                                                ⎥
⎢40 + 86⋅ⅈ  98 + 81⋅ⅈ  6 + 77⋅ⅈ   9 + 49⋅ⅈ   49 + 26⋅ⅈ  96 + 97⋅ⅈ⎥
⎢                                                                ⎥
⎢14 + 34⋅ⅈ  88 + 52⋅ⅈ  26 + 12⋅ⅈ  73 + 80⋅ⅈ  22 + 45⋅ⅈ  30 + 60⋅ⅈ⎥
⎢                                                                ⎥
⎢93 + 40⋅ⅈ  70 + 52⋅ⅈ  74 + 24⋅ⅈ  21 + 8⋅ⅈ   71 + 66⋅ⅈ  10 + 51⋅ⅈ⎥
⎢                                                                ⎥
⎣16 + 20⋅ⅈ  60 + 60⋅ⅈ    42⋅ⅈ     41 + 92⋅ⅈ  37 + 54⋅ⅈ  59 + 78⋅ⅈ⎦
```

So `DomainMatrix` can bring enormous speed up in matrix computations. The difference is much more significant than any tweaking of `Matrix` methods could possibly bring. The task now is to make `DomainMatrix` complete and to make use of it in order to speed up calculations with `Matrix`.

## Docs for DomainMatrix

The most immediate thing that needs doing is to add docs for DomainMatrix. Few of the methods have docstrings and there is no page in the docs that lists any of the classes or methods.
**DomainMatrix urgently needs docs**

## Immutable matrices

In the case of a matrix of all integers or rationals DomainMatrix is compatible with Matrix so it would be possible to make such matrices always use DomainMatrix internally. We could therefore check when a Matrix is created whether or not all the elements are integers and if so convert the representation internally into a DomainMatrix. A major problem though is that Matrix is mutable so the fact that a matrix is created with all integer elements does not mean that it won't have non-integers inserted later. In fact a very common pattern with Matrix is to begin by creating a matrix of all zeros and then insert the nonzero elements after e.g.:
```python
In [15]: M = zeros(2, 2)

In [16]: M
Out[16]: 
⎡0  0⎤
⎢    ⎥
⎣0  0⎦

In [17]: M[0, 0] = sqrt(2)

In [18]: M
Out[18]: 
⎡√2  0⎤
⎢     ⎥
⎣0   0⎦
```
This would be problematic with DomainMatrix because it implies the possible need to change domain every time an assignment occurs. Changing domain would require converting every element in the matrix from one domain to another. This is not a problem though for immutable matrices:
**We could make it so that immutable matrices use DomainMatrix for their internal representation if all elements are integer or rational**.
One way to do this would be to introduce a subclass of ImmutableMatrix that overrides the other methods to use an internal DomainMatrix. Then the ImmutableMatrix constructor could check if all elements are integer/rational and return an instance of the subclass instead.

## Slow matrix methods

The reason that DomainMatrix is not compatible with Matrix in all cases is because the domain system canonicalises the representations of all expressions. For example with Matrix an element could be an expression like `(x + 1)**100` but in DomainMatrix that polynomial would have to be expanded. Most of the time this makes DomainMatrix a lot faster but there are at least some cases where it would be a lot slower as a result. Many matrix operations need to expand polynomials like this anyway though such as `charpoly`, `rref`, etc. The `DomainMatrix` class can be much more efficient than `Matrix` for something like `rref` (or any operation that involves row reduction) precisely because it automatically uses canonicalised forms that provide easy zero-testing. By contrast functions like `Matrix.rref` need to use e.g. `simplify` in order to determine if a possible pivot is nonzero.

We should identify those functions that are potentially slow with Matrix that can be made faster simply by converting to `DomainMatrix` without any significant compatibility problems. Generally this is the case for `charpoly` and also any function that uses row reduction e.g.: `det`, `charpoly`, `eigenvals`, `eigenvects`, `jordan_form`, `inv`, `echelon_form`, `nullspace`, `rank` and more.

Already `eigenvects` was made to use `DomainMatrix` internally in #20614 and it is now a lot faster as a result and can also handle matrices larger than 4x4. The `eigenvects` computation is not much different from `jordan_form` though which is potentially more useful as it is used for the matrix exponential. 

**We should have Matrix.jordan_form and Matrix.charpoly etc convert to DomainMatrix to perform the computation.**

## DomainMatrix utilities

Currently the DomainMatrix class lacks basic utility methods such as slicing. These should be added to the `DomainMatrix` class but not necessarily to the lower level `DDM` or `SDM` classes. For example `DDM` and `SDM` subclass `list` and `dict` respectively so that they have fast built-in `__getitem__` and `__iter__` methods. The `DomainMatrix` class can support slicing through `__getitem__` without compromising the speed of the lower-level classes that could expose methods like `getslice()` to implement these operations efficiently.

**We should list here the utilities that are needed and add them**

## Dense vs sparse

We need to figure out how the dense and sparse implementations of DomainMatrix can coexist. These are the lower-level classes `DDM` and `SDM` that subclass `list` and `dict` respectively. There should be some way of deciding when it would be better for `DomainMatrix` to use the sparse `SDM` class or otherwise the dense `DDM` class. At the time of writing I think that the internal representation will always be `SDM` (since #20780). I think it would be better to sometimes use dense and sometimes use sparse although `DomainMatrix` itself should hide this detail from the user.

There are obvious benefits to the sparse representation that whenever there is any significant sparsity (which can be hard to predict ahead of time) the calculations can be enormously faster.

**The question then is: when is it significantly better to use the dense representation rather than the sparse representation?**

I think that the answer to the question is that the dense representation has a lower overhead if the matrix is fully dense. This is easily dwarfed though by the cost of the arithmetic unless the arithmetic is cheap. In particular the domains with cheap arithmetic are `ZZ` and `QQ` (if gmpy is installed). For those it can be better to use the dense representation in some cases. Every other domain has even more complicated arithmetic so it might be the case that there is never any significant benefit in using the dense representation for domains other than `ZZ` or `QQ`.

In the case of matrix multiplication it seems that for `ZZ` the dense representation is roughly 3x faster for matrices with 100% density. The sparse representation can be enormously faster as the density approaches 0%. The breakeven point is around 25% density where both implementations perform equally well. However with `QQ` already the benefit of the dense representation is reduced because the arithmetic is much more expensive. The breakeven point for `QQ` is around 75% density and the speedup offered by dense at 100% density is small.

This breakeven point is different for different operations though. In the case of `rref` the sparse implementation seems to be faster than the dense implementation even for fully dense matrices so there is never any benefit in using the dense implementation.

## DomainScalar?

The PR #20614 used DomainMatrix to speed up the `Matrix.eigenvects` function. In that PR it emerged that the implementation could be a lot simpler if it was possible to support multiplication of `DomainMatrix` with a scalar. This is possible if the scalar is an element of the domain of the matrix but not otherwise e.g.:
```python
In [20]: dM = DomainMatrix.from_Matrix(Matrix([[1, 2], [3, 4]]))

In [21]: dM
Out[21]: DomainMatrix([[1, 2], [3, 4]], (2, 2), ZZ)

In [22]: 3*dM
Out[22]: DomainMatrix([[3, 6], [9, 12]], (2, 2), ZZ)

In [23]: (S(3)/2)*dM
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-9b550b791378> in <module>
----> 1 (S(3)/2)*dM

TypeError: unsupported operand type(s) for *: 'Rational' and 'DomainMatrix'
```
For something like eigenvector computation you want to compute e.g. `nullspace(M - lambda*I)` where `M` is the matrix and `lambda` is an eigenvalue. The problem is that the eigenvalue is not necessarily an element of the domain of `M` e.g. `M` might have `QQ` as its domain but the eigenvalue might be `sqrt(2)` which is an element of the larger domain `QQ<sqrt(2)>`.

I think that a clean way to make this work would be to introduce a `DomainScalar` class which wraps up both a domain element along with its domain and supports e.g. unification of domains. Then indexing into a `DomainMatrix` could return a `DomainScalar` and `DomainMatrix` would know how to multiplied/divided by a `DomainScalar` so `M - lambda*I` would be able to automatically unify the domains. The `DomainScalar` class could be something like:
```python
class DomainScalar:

    def __init__(self, element, domain):
        self.element = element
        self.domain = domain

    @classmethod
    def new(cls, element, domain):
        return cls(element, domain)

    def __repr__(self):
        return repr(self.element)

    @classmethod
    def from_sympy(cls, expr):
        [domain, [element]] = construct_domain([expr])
        return cls.new(element, domain)

    def to_domain(self, domain):
        element = domain.convert_from(self.element, self.domain)
        return self.new(element, domain)

    def unify(self, other):
        domain = self.domain.unify(other.domain)
        return self.to_domain(domain), other.to_domain(domain)

    def __add__(self, other):
        if not isinstance(other, DomainScalar):
            return NotImplemented
        self, other = self.unify(other)
        return self.new(self.element + other.element, self.domain)
```
**Add DomainScalar class?**

## Fraction-free algorithms

One of the things that is sometimes slow with `DomainMatrix` (although still usually faster than `Matrix`) is cancellation in a rational function field. A rational function field like `QQ(x)` represents each element as a ratio of two polynomials like `p(x)/q(x)`. Creating each element leads to cancellation of common factors which means calling `gcd(p(x), q(x))` which can be slow. The gcd calculations should be made faster (#20874) but it will still generally be beneficial for `DomainMatrix` to use fraction free algorithms such as the Bareiss algorithm.

In the current implementation of `DomainMatrix.rref` all calculations are done in a fraction field like `QQ(x)` even if the elements of the matrix can all be represented in a polynomial ring like `QQ[x]`. In some cases this makes the calculations a lot slower than they could be. It should be possible to work in the ring `QQ[x]` using something like the Bareiss algorithm to at least get the matrix into echelon form. In principle I think it is possible to delay converting to a field until the final step and then divide by each of the pivots.

**We should add fraction free row reduction for `det` and anything else**

## Charpoly-based approaches

For square matrices we can compute the characteristic polynomial using the Berkowitz algorithm and use that for other calculations. This is implemented for the dense representation of `DomainMatrix` and is very fast. The implementation should probably be made to work at the `DomainMatrix` rather than `DDM` level so that it can work for `SDM` as well.

In #20483 I have added faster inverse computation based on the characteristic polynomial. This works precisely because the calculations are performed in the ring rather than the fraction field. For example if the matrix `M` has characteristic polynomial `a*x**3 + b*x**2 + c*x + d` then the matrix itself satisfies
```
a*M**3 + b*M**2 + c*M + d*I = 0
```
Multiplying by the inverse `M**-1` we get
```
a*M**2 + b*M + c*I + d*M**-1 = 0
```
or in other words
```
d*M**-1 = - a*M**2 - b*M - c*I
```
Here `d` the constant term of the characteristic polynomial is actually `det(M)`. What this shows is that we can compute the inverse from the characteristic polynomial using only a single division by `det(M)` at the end.

Matrix polynomials such as the rhs here can be computed most efficiently using the Paterson–Stockmeyer method with only `sqrt(N)` matrix-matrix multiplies. If fully implemented this would probably speed up matrix-inverse computation substantially.

We can use a related technique to solve systems of equations like `M*x = y`. If `M` is square and invertible then the solution is `x = M**-1 y` but using the characteristic polynomial that is
```
- d*x = (a*M**2 + b*M + c*I)*y
```
Here we can compute `-d*x` using only matrix-vector multiplies (no matrix-matrix products) in a ring and then perform a single division by `d` at the end. Since square systems of equations are common this could be a big speedup for many common cases.

**Add the Paterson-Stockmeyer algorithm and use it for computing inverse. Add a routine to use charpoly to solve square systems of equations**

## Speed up integrals

Both the risch and heurisch integration routines make use of solving sparse systems of linear equations over the poly domains so they can both benefit from DomainMatrix. SymPy's integration routines can be extremely slow and improving and using `DomainMatrix` in the integration routines is an important way that we can make integration much faster for many cases.

Currently heurisch uses DomainMatrix (via `solve_lin_sys`) but it does not make full use of the sparse implementation so the slowest part is sparse-to-dense conversion in the output of `solve_lin_sys`. Try profiling this example for a demonstration:
```python
t = Symbol('t')
integrate((sin(t)**2 + 2*cos(t))*sqrt(3*sin(t)**2 + 1), (t, 0, 2*pi))
```
(Note, if you profile this that the most immediately slow thing is a call to `has` that can be made faster by using `free_symbols`.) The other slow part in heurisch is converting between Expr and the polys domains. The notes in the heurisch code say that Expr is used because the polys gcd calculations are too slow to just use the polys domains everywhere. I'm not sure if that's still true but I think ideally the whole calculation would be done in the polys domains and then DomainMatrix could be much faster at solving the sparse linear systems that come up.

**Make heurisch faster by using the sparse implementation of DomainMatrix efficiently**

The risch routine uses PolyMatrix rather than DomainMatrix but could be made faster if it was ported to DomainMatrix. PolyMatrix itself could be made faster if it was implemented on top of DomainMatrix but I suspect that what would be best for risch is just to use DomainMatrix. Porting this over is tricky because PolyMatrix mixes Expr/Poly in different places and so does the risch code. To use DomainMatrix the boundary between domain elements and Expr needs to be very clear so that conversion happens in the right places.

**Make risch faster by having it use DomainMatrix**

## More things?

I'm sure there's plenty more to do...

**Comment by sylee957** [comment]
My opinion is we shouldn't do `Make ImmutableMatrix use DomainMatrix internally if all elements are integer/rational.`.

I also that how `gcd` or `integrate` work with Expr works in the steps of
1. Parse Expr into Domain
2. Compute
3. Parse Domain into Expr

And for speeding up the `rref` or `solve`, we should rather do the steps of
1. Parse Matrix into DomainMatrix
2. ...
3. ...

You may be concerned about the speed of converting the element every time if multiplication or `rref` is performed, but I think that it's really builds up an incomplete system than Expr if the optimization only works with only a tiny set of expressions.

**Comment by oscarbenjamin** [comment]
> My opinion is we shouldn't do `Make ImmutableMatrix use DomainMatrix internally if all elements are integer/rational.`.

Okay, maybe that part isn't worth doing.

> You may be concerned about the speed of converting the element every time if multiplication or `rref` is performed

The cost of conversion can be bigger than the cost of the internal computation. There is potential to optimise the conversion itself though.

**Comment by oscarbenjamin** [comment]
I already said this in https://github.com/sympy/sympy/pull/21037#issuecomment-798775624 bit I think it's worth restating here on the main issue:

The current Matrix implementation of many algorithms has a bunch of heuristic fixes to try and make faster for some cases by using e.g. dotprodsimp, cancel, simplify etc. Many of those fixes are to handle cases that are actually better handled by DomainMatrix for domains like `QQ<sqrt(2)>` or `QQ_I` etc. If we can make use of DomainMatrix to make those cases faster then we can remove things like dotprodsimp from the main Matrix methods to make them faster in the cases that do not use DomainMatrix. It's also possible that we can better optimise the cases that are handled by DomainMatrix by e.g. making better use of sparse methods (charpoly currently uses the dense implementation).

**Comment by oscarbenjamin** [comment]
I think that `__getitem__` for `DomainMatrix` should not support single index access and I don't think that `DomainMatrix` should have `__iter__`. With `Matrix` you can do e.g.
```python
In [5]: M = randMatrix(2)

In [6]: M
Out[6]: 
⎡8   89⎤
⎢      ⎥
⎣75  82⎦

In [7]: M[0]
Out[7]: 8

In [8]: M[1]
Out[8]: 89

In [11]: for x in M: print(x)
8
89
75
82
```
I don't think Matrix should work like that and I don't think that DomainMatrix should copy that behaviour.

The behaviour of `Matrix.__iter__` would be better as an attribute e.g. `M.flat` (or something consistent with numpy).

The `__getitem__` method should support:

1. Double indexing `M[i, j]`
2. Slicing `M[:-1, :-1]`

I think that index access like `M[i, j]` should give a `DomainScalar` so that you can use it with other matrices.

**Comment by oscarbenjamin** [comment]
It seems that a lot of the places where we would potentially use DomainMatrix need to check whether the Matrix has entries that are Expr and also what domain would be used by DomainMatrix. Perhaps a helper function should be created to efficiently check what domain would be used.

Perhaps also there could be a `Matrix.to_DomainMatrix` method.

**Comment by sylee957** [comment]
My opinion is we could have consolidated keyword like `domain='QQ'`,
and `domain='auto'` or `domain=None` delegated for figuring out the best domain to encode (usual) real and complex arithmetics.
We also had other inquiries like #19001 which can be fixed simply by making the domain as user option.

For default, we should work out the best way to parse usual real and complex expression into isomorphic domain and encode everything as field, or we can hit on other problems like divisibility.
I'm not sure if this is the scope for this, but I'm aware that there are more generalized to define polynomials like (https://www.maa.org/sites/default/files/pdf/pubs/amm_supplements/Monthly_Reference_13.pdf) than (usual) univariate or multivariate polynomials to fix the problems of exponential or trigonometric expressions.

**Comment by oscarbenjamin** [comment]
> My opinion is we could have consolidated keyword like `domain='QQ'`,
> and `domain='auto'` or `domain=None` delegated for figuring out the best domain to encode (usual) real and complex arithmetics.

I think I agree but I'm not entirely sure what you mean.

> We also had other inquiries like #19001 which can be fixed simply by making the domain as user option.

I agree. I think that we need another class that can sit on top of `DomainMatrix` and that is `Expr` and allows users to specify the domain but supports all operations with `Expr` including returning `Expr` from indexing like `M[i, j]`.

**Comment by sylee957** [comment]
I had distractive point of view about the past,
But what I mean is 
`domain='ZZ'`, `domain='QQ'`, ... -> Explicit specification, it should always convert to domain matrix and it should fail if it gives coercion error
`domain=finite field` -> If you want the alterative to integers.
`domain=None` -> Try to parse rational, polynomial, algebraic at the best, with careful time penalty analysis.

> I think that we need another class that can sit on top of DomainMatrix and that is Expr and allows users to specify the domain but supports all operations with Expr including returning Expr from indexing like M[i, j].

This can eliminate the need of `domain=` keyword approach, but I think that this needs a careful design option how to implement things internally or we end up with the same problems like `Poly`

**Comment by oscarbenjamin** [comment]
> This can eliminate the need of `domain=` keyword approach

We would still need the `domain=` argument so that users can specify e.g. a finite field or in some cases the choice of domain can be ambiguous or they might want to use a specially constructed domain.

> but I think that this needs a careful design option how to implement things internally or we end up with the same problems like `Poly`

Can you clarify what you mean by "the same problems like `Poly`"?

**Comment by oscarbenjamin** [comment]
The `SDM.matmul` method can be made a lot faster. Currently it is actually optimised for the dense case but it can be quite slow for a typical sparse matrix e.g.:
```python
In [1]: M = eye(1000)

In [2]: from sympy.polys.domainmatrix import DomainMatrix

In [3]: dM = DomainMatrix.from_Matrix(M)

In [4]: %time ok = dM * dM
CPU times: user 362 ms, sys: 2.29 ms, total: 364 ms
Wall time: 363 ms
```
The diff below (click to see) makes this 100x faster:
```python
In [4]: %time ok = dM * dM
CPU times: user 3.14 ms, sys: 104 µs, total: 3.24 ms
Wall time: 3.26 ms
```
Also ideally most methods on `SDM`/`DDM` would be implemented in functions like `sdm_transpose()` that just operate on dicts/lists. We should put those functions in a module `sparse.py` (analogous to `dense.py`). They form the lowest level of the implementation of `DomainMatrix` and the idea is that they could be reimplemented easily in another language like `C++`.

<details><summary>CLICK ME TO SEE THE DIFF</summary>
<p>

```diff
diff --git a/sympy/polys/matrices/sdm.py b/sympy/polys/matrices/sdm.py
index 26d2e5744c..a5b73e966b 100644
--- a/sympy/polys/matrices/sdm.py
+++ b/sympy/polys/matrices/sdm.py
@@ -73,13 +73,7 @@ def eye(cls, size, domain):
         return cls(sdm, (size, size), domain)
 
     def transpose(M):
-        MT = {}
-        for i, Mi in M.items():
-            for j, Mij in Mi.items():
-                try:
-                    MT[j][i] = Mij
-                except KeyError:
-                    MT[j] = {i: Mij}
+        MT = sdm_transpose(M)
         return M.new(MT, M.shape[::-1], M.domain)
 
     def __mul__(a, b):
@@ -97,22 +91,8 @@ def __rmul__(a, b):
     def matmul(A, B):
         if A.domain != B.domain:
             raise DDMDomainError
-        zero = A.domain.zero
-        C = {}
-        BT = B.transpose()
-        for i, Ai in A.items():
-            Ai_ks = set(Ai)
-            Ci = {}
-            for j, BTj in BT.items():
-                BTj_ks = set(BTj)
-                knonzero = Ai_ks & BTj_ks
-                if knonzero:
-                    terms = (Ai[k] * BTj[k] for k in knonzero)
-                    Cij = sum(terms, zero)
-                    if Cij:
-                        Ci[j] = Cij
-            if Ci:
-                C[i] = Ci
+        K = A.domain
+        C = sdm_matmul_dense(A, B, K.zero, K.one)
         return A.new(C, A.shape, A.domain)
 
     def mul(A, b):
@@ -234,6 +214,83 @@ def unop_dict(A, f):
     return B
 
 
+def sdm_transpose(M):
+    MT = {}
+    for i, Mi in M.items():
+        for j, Mij in Mi.items():
+            try:
+                MT[j][i] = Mij
+            except KeyError:
+                MT[j] = {i: Mij}
+    return MT
+
+
+def sdm_matmul_dense(A, B, zero, one):
+    #
+    # Slightly faster than sdm_matmul_sparse if A and B are quite dense.
+    # Perhaps not really worth it because SDM is really supposed to be
+    # efficient for sparse matrices and sdm_matmul_sparse is much faster whrn
+    # A and B are properly sparse.
+    #
+    C = {}
+    BT = sdm_transpose(B)
+    for i, Ai in A.items():
+        Ai_ks = set(Ai)
+        Ci = {}
+        for j, BTj in BT.items():
+            BTj_ks = set(BTj)
+            knonzero = Ai_ks & BTj_ks
+            if knonzero:
+                terms = (Ai[k] * BTj[k] for k in knonzero)
+                Cij = sum(terms, zero)
+                if Cij:
+                    Ci[j] = Cij
+        if Ci:
+            C[i] = Ci
+    return C
+
+
+def sdm_matmul_sparse(A, B):
+    #
+    # A lot faster then sdm_matmul_dense if A and B are very sparse.
+    # Consider e.g. A = B = eye(1000).
+    #
+    # The idea here is that we compute C = A*B in terms of the rows of C and
+    # B since the dict of dicts representation naturally stores the matrix as
+    # rows. The ith row of C (Ci) is equal to the sum of Aik * Bk where Bk is
+    # the kth row of B. The algorithm below loops over each nonzero element
+    # Aik of A and if the corresponding row Bj is nonzero then we do
+    #    Ci += Aik * Bk.
+    # To make this more efficient we don't need to loop over all elements Aik.
+    # Instead for each row Ai we compute the intersection of the nonzero
+    # columns in Ai with the nonzero rows in B. That gives the k such that
+    # Aik and Bk are both nonzero. In Python the intersection of two sets
+    # of int can be computed very efficiently.
+    #
+    C = {}
+    B_knz = set(B)
+    for i, Ai in A.items():
+        Ci = {}
+        Ai_knz = set(Ai)
+        for k in Ai_knz & B_knz:
+            Aik = Ai[k]
+            for j, Bkj in B[k].items():
+                Cij = Ci.get(j, None)
+                if Cij is not None:
+                    Cij = Cij + Aik * Bkj
+                    if Cij:
+                        Ci[j] = Cij
+                    else:
+                        Ci.pop(j)
+                else:
+                    Cij = Aik * Bkj
+                    if Cij:
+                        Ci[j] = Cij
+        if Ci:
+            C[i] = Ci
+    return C
+
+
 def sdm_irref(A):
     """RREF and pivots of a sparse matrix *A*.
```

</p>
</details>

**Comment by oscarbenjamin** [comment]
I've come up with a better idea for how to integrate `DomainMatrix` and `Matrix` so that there is a single implementation of matrices and so that we can make `Matrix` faster.

Ideally we would just make it so that a `Matrix` has an internal `DomainMatrix` that it delegates its operations to. Then e.g. `Matrix.__add__` would just do something like `return Matrix.from_rep(self.rep + other.rep)` and so `Matrix` itself is just a wrapper around `DomainMatrix`. The difficulties in doing this are:

1. It isn't backwards compatible to use e.g. `ZZ[x]` for any matrix with polynomial expressions because that expands every polynomial expression like `(x + 1)**2`. The only domains that are completely compatible with the current behaviour of `Matrix` are `ZZ` and `QQ`.
2. The `EX` domain is not compatible with `Expr` since every arithmetic operation calls `cancel` and this also makes `EX` slow.
3. A number of places around the codebase use `Matrix` with non-`Expr` elements that could never be converted to any domain.

I think that a solution (at least for 1. and 2.) is to make a new pseudo-domain called something like `EXRAW` or `EXPR` that uses `Expr` as its elements but does not call `cancel`. This would be a domain in which zero-checking doesn't work at all but it would still be suitable for ring operations like addition and multiplication. For `EX` the domain elements are instances of `Expression` that internally hold `Expr` instances. For `EXRAW` the elements would literally be `Expr` instances and all operations like `*` and `+` would simply delegate directly to `Expr`.

Using the `EXRAW` domain would make `DomainMatrix` more directly compatible with `Matrix`. The strategy could be to make it so that calling `Matrix(...)` internally constructs a `DomainMatrix` using either the `ZZ`, `QQ` or `EXRAW` domains. That can then be used for addition, multiplication, slicing etc. Operations that need zero-testing such as `rref` would then attempt to convert `EXRAW` to another domain like `ZZ_I` or `ZZ[x]` (or potentially `EX`).

Following this approach would mean that:

1. There is one place to focus on micro-optimisations for all matrix classes.
2. Classes like SparseMatrix become immediately redundant (DomainMatrix would always be sparse internally).
3. It is possible to make the transition in a backward compatible way (perhaps later changes could break strict compatibility e.g. by using `ZZ_I` or `QQ_I` by default).
4. Matrix could immediately become faster for many operations.
5. The `DomainMatrix` class itself would be more well tested.

Ultimately the design of the `Matrix` class is a big mess and I would like to build something new. Having it depend on `DomainMatrix` for all the heavy lifting would make it straight-forward to build a new interface over that in future.

**Comment by sylee957** [comment]
How should EXRAW be opted for more general usage?
I think that the biggest concern for introducing new EX domain is that it fails to generalize for much usage (and this was one of the reason why we couldn’t use old EX because it relies on simplify)

I think that it needs some thorough abstraction to enable the ability to specify canonical/normal forms, how to pick numerator and denominator, ...

**Comment by oscarbenjamin** [comment]
> How should EXRAW be opted for more general usage?

I'm not sure that it should have more general usage. I'm just thinking of it as a placeholder that allows `DomainMatrix` to work with Expr like Matrix does for some operations for backwards compatibility.

**Comment by sylee957** [comment]
I think that the old matrix also involves the usage of sympy assumptions, which can be a problem for migrating to use DomainElement.

**Comment by oscarbenjamin** [comment]
Note that `DomainElement` would not be involved here. The "elements" would just be `Expr` instances. The "domain" here is just a dummy domain object the provides the interface `DomainMatrix` needs (`one`, `zero`, `from_sympy`, `convert_from`, ...) in order to do basic operations with Expr as the elements of the matrix.

I think you are imagining something more complicated than what I am proposing which is really just a shim that allows all `Matrix` to use `DomainMatrix` internally while still just using `Expr` for some basic operations (to preserve compatibility).

**Comment by asmeurer** [comment]
The problem as I see it is that the polys domains serve as a restricted computation domain that allow computing on a specific type of representation. This has two advantages, the representation can lead to faster computations, and the restricted domain can lead to exact results. For example, dense polynomials Q[x] are represented as a list of coefficients, which is much faster to manipulate than a symbolic expression tree, and polynomials themselves have nicer properties than general expressions (e.g., exact fast zero equivalence checking). 

The issue is that any expression that fits this restricted set of must be canonicalised into the given representation, so for instance, polynomials must be expanded. If this canonicalization is itself slow or leads to an explosion in size, the benefits are lost. Another example is algebraic extensions, which become slow, at least under the current state of things, if there are too many (but the advantage is again things like exact zero equivalence). 

The polynomial expansion problem is a general problem in the domains. See for instance https://github.com/sympy/sympy/issues/6322. I think we need a domain that allows computations on unexpanded polynomials, but still in an efficient way. Some computations would not be possible without expanding, so they would either have to explicitly do that or error. But quite a few things are already possible, for instance, by using the code in `series`, but it just isn't tied together into a poly domain that can be reused in the places that use the polys. The underlying "base" polynomials could also be poly objects instead of Expr, if that helps with performance. Basically a pseudo expression tree built on top of Poly, which is more limited, for instance, exponents can only be integers.

**Comment by drmikecooke** [comment]
I am somewhat baffled by the DomainScalar type. I constructed a matrix:

```
from sympy import ZZ
from sympy.polys.matrices import DM

D=ZZ['x']

x,=D.gens

M=DM([[1,x,x**2],[x,x**2,x**3]],D)
```

If I want to use the element ```M[0,1]```, I would expect to be able to use it in my domain ```D```. But alas:

```x*M[0,1]```

gives the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 x*M[0,0]

TypeError: unsupported operand type(s) for *: 'PolyElement' and 'DomainScalar'
```

To do this sort of thing, I seem to have to convert to a list of lists:

```
M.to_list()[0][1]*x
```

which to a naive person such as myself seems daft?

**Comment by oscarbenjamin** [comment]
I think maybe the DomainScalar type was a mistake. It would be better if indexing a DomainMatrix gives ordinary domain elements. The intention of DomainScalar is that it makes it possible for a scalar of a different domain to multiply the DomainMatrix and for the domain of the matrix to be promoted implicitly.
