### ISSUE TITLE
Releasing SymPy 1.11

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23740]
This issue is to track the release of sympy 1.11. The release notes for 1.11 are here:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.11

The issue for the previous release 1.10 is #22963

The release branch for 1.11 will be created shortly.

The list of issues and PRs with the 1.11 milestone is here:
https://github.com/sympy/sympy/milestone/61

Todo:

- [x] Clean up the release notes (#23743)
  - [x] Bring all deprecations and breaking changes up to the top.
  - [x] Mention any highlights
  - [x] Clear up wording of notes.
  - [x] Aggregate similar notes?

- [x] Set up the release branch and versions:
  - [x] Open a PR to update the version on the master branch to 1.12.dev. #23779
  - [x] Create the release notes page for 1.12: https://github.com/sympy/sympy/wiki/Release-Notes-for-1.12
    - [x] Check that the supported Python versions for 1.11 are correct
    - [x] Check if the supported Python versions for 1.12 should be changed (not needed. Current is 3.8 to 3.11 and 3.7 is not even EOL yet).
       - [x] Update changes in the release notes
       - [x] Update changes in CI and setup.py, benchmarks etc.
  - [x] Open a PR to update the AUTHORS file. #23781
    - [x] Check if author names look correct and maybe contact some authors for clarification (shouldn't be necessary with the new mailmap changes).
  - [x] Merge the updated AUTHORS file and then immediately... #23781
  - [x] ... Create the 1.11 release branch and then immediately...
  - [x] ... Merge the master branch version update. #23779
  - [x] Change the version on the release branch to 1.11rc1 #23782
  - [x] Fix the benchmarks on the release branch #23790

- [ ] Clean up release scripts
   - [ ] Open a PR to add a new README and keep it updated #23780.
   - [x] Move old scripts into a directory like "old_release_files". Actually just delete them: #23793
  - [x] Update the pinned dependencies in requirements.txt for the release branch. Actually just delete them #23791
  - [x] Use the doc installer files for building the release files #23791
  - [x] Add the `compare_tar_against_git.py` check to `runtests.yml` so it runs on all PRs #23791
  - [x] Forward port these changes from CI to the master branch: #23793 
  - [x] Fix up #23797

- [x] Resolve all issues and PRs with the 1.11 tag, backporting to the 1.11 branch if necessary.

- [x] Issue a release candidate
  - [x] Make a tag `sympy-1.11rc1`.
  - [x] Upload the release files to GitHub
  - [x] Upload the release files to PyPI
  - [x] Email announcement to the mailing list

- [x] Wait to see if problems are reported with rc1. More RCs needed?

- [x] Make a final release
  - [x] Change version to 1.11 in `sympy/release.py`
  - [x] Make a `sympy-1.11` tag
  - [x] Upload the release files to GitHub
  - [x] Upload the release files to PyPI
  - [x] Update the docs website
    - [x] Change versions.json
  - [x] Make an announcement to the mailing list
  - [x] Add SHA and Authors to the release notes

- [ ] Wait to see reports of regressions. Bugfix release needed?

**Comment by asmeurer** [comment]
> Some of the warnings are actually things that should be fixed though such as using deprecated scipy functions or np.matrix. It would be good to split that into separate issues to track what actually needs to be fixed and then maybe in the short term just add ignore_warnings to the associated tests.

In this case, it's just a test that np.matrix works correctly. So ignore_warnings is the correct fix.

**Comment by agryman** [comment]
@oscarbenjamin I'm not familiar will the release process. I assume SymPy 1.11 contain everything currently in master. I am particularly interested in seeing https://github.com/sympy/sympy/pull/23659 https://github.com/sympy/sympy/issues/23647 included in 1.11. Thanks.

**Comment by oscarbenjamin** [comment]
> I am particularly interested in seeing #23659 #23647 included in 1.11

Those are both already merged to master. Since the release branch has not yet been created they will be included in the release along with anything else currently merged to master.

Once the release branch is created changes merged to master will not automatically become part of the 1.11 release but they can still be backported by also opening a PR against the release branch.

**Comment by agryman** [comment]
@oscarbenjamin Glad to hear that. Thanks for the explanation.
