### ISSUE TITLE
Laplace and Inverse Laplace: Work plan

### ISSUE THREAD

**Issue by hanspi42** [sympy/sympy#24561]
The complete re-write for the Laplace (LT) and inverse Laplace (ILT) transform will take considerable time and many steps/PRs. This first entry of this issue shows my plan present work plan, which I will keep on editing. Please comment if you have questions / suggestions, and check back. This list will change often ;)

To Do:
- [ ] ILT: Re-write ILT to give it the same structure as LT, and implement the rules necessary for rational expressions. Fixes #23623 and #24424.
- [ ] LT: Reduce time taken to build rules.
- [ ] LT: Re-check issue #7219
- [ ] ILT: Implement more rules useful for all expressions coming system theory.
- [ ] ILT: Improve partial fraction decomposition.
- [ ] LT: Improve formulae for trig rules.
- [ ] LT: Make it possible to use only rules or only integration.
- [ ] LT: Make simplify default to False.
- [ ] LT: Continue with #17098
- [ ] LT: Deal with integrals,  #24545
- [ ] LT: Deal with sums, #7177

**Comment by sylee957** [comment]
I think that laplace transform could be first moved to separate file because it looks very large to add more stuff to transforms.pu

**Comment by hanspi42** [comment]
This sounds reasonable, but I don't know at all how to do it. Would you have time to make that move?

**Comment by sylee957** [comment]
I'm doing that changes in #24563

**Comment by jksuom** [comment]
There are two Laplace transforms, 1-sided and 2-sided. Maybe there should be two inverse transforms as well.

**Comment by oscarbenjamin** [comment]
@hanspi42 feel free to review #24563

**Comment by hanspi42** [comment]
> I'm doing that changes in #24563

Thank you!

> There are two Laplace transforms, 1-sided and 2-sided. Maybe there should be two inverse transforms as well.

I'll take it into the list, but low priority, since it can be done by users who need it by doing two one-sided LTs or by removing the `Heaviside(t)` from the one-sided result.

**Comment by sylee957** [comment]
I'm doing some work to clean up the laplace transform table for in #24567 for redundant entries `dco`. 
You'd also take a look at it

**Comment by hanspi42** [comment]
> I'm doing some work to clean up the laplace transform table for in #24567 for redundant entries `dco`.
> You'd also take a look at it

It is not going to remain redundant; please don't touch this! I put it into the work list.

**Comment by hanspi42** [comment]
My ultimate goal is, by the way, that it will never happen that integration will be called and succeed in both LT and ILT.

**Comment by sylee957** [comment]
Okay, I hope to see if things are nontrivial in inverse transforms.
But I'd structure things differently if it already shares stuff too much common.

**Comment by hanspi42** [comment]
We will be reaching the point soon where `simplify=False` becomes the default. Should we make `noconds=True` the default at the same time? I think most users don't care about convergence planes or conditions and would rather ask for them explicitly if they want them.

**Comment by oscarbenjamin** [comment]
> Should we make `noconds=True` the default at the same time?

It's not backwards compatible though because users are almost certainly doing this:
```python
In [17]: laplace_transform(t, t, s)[0]
Out[17]: 
1 
──
 2
s 

In [18]: laplace_transform(t, t, s, noconds=True)[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-ad97e6728b8e> in <module>
----> 1 laplace_transform(t, t, s, noconds=True)[0]

TypeError: 'Pow' object is not subscriptable
```

**Comment by hanspi42** [comment]
> It's not backwards compatible though

Yes, I know. But I don't like it that `laplace_transform` and `LaplaceTransform().doit()` do not have the same standard setting.  The question is whether making it more consistent is enough of a reason to break backwards compatibility. I have my doubts but thought I'd better ask.

**Comment by oscarbenjamin** [comment]
Changing `doit` is a bug fix because `doit` should not behave like that when part of any expression. Changing `laplace_transform` to use noconds is not a bug fix though.

**Comment by hanspi42** [comment]
> Changing `doit` is a bug fix because `doit` should not behave like that when part of any expression. Changing `laplace_transform` to use noconds is not a bug fix though.

Understood. So let's keep `noconds` as is.

**Comment by hanspi42** [comment]
We will be reaching the point soon where `simplify=False` becomes the default. The idea behind this was that it is the `simplify` that often consumes most of the computation time. There are to views:
 - `simplify=True` is the default because it serves most people well, and it is possible to switch it to `False` to save time.
 - `simplify=False` is the default because setting it to `True` violates the single-responsibility principle as simplification is not needed for a successful LT or ILT, and depending on the expression, an indiscriminate `simplify` is not the best thing to do.

Changing this will change the results of a lot of test cases, and virtually everyone out there will be affected. However, since we are already making massive changes to the LT and ILT in SymPy 12, massive changes happen anyway, so if there is a time to do it, it is actually now.

@asmeurer, @sylee957, @oscarbenjamin: please help me decide. The change in `laplace.py` will be minimal, in `test_laplace.py` it will be extensive.

**Comment by hanspi42** [comment]
After asking Caltech and discussing with @oscarbenjamin , I have made Bateman54 with my notes available here: https://github.com/sympy/sympy-development-docs

**Comment by gabemorris12** [comment]
Hey guys! I appreciate all the work y'all are doing. This is quite impressive. I am particularly looking forward to the implementation of adding values in for the initial condition of derivatives. After that comes, we will be able to handle transfer functions more efficiently and actually solve ODE's using laplace transform methods. Anyways, I just wanted to extend my gratitude!

**Comment by hanspi42** [comment]
> Hey guys! I appreciate all the work y'all are doing. This is quite impressive. I am particularly looking forward to the implementation of adding values in for the initial condition of derivatives. After that comes, we will be able to handle transfer functions more efficiently and actually solve ODE's using laplace transform methods. Anyways, I just wanted to extend my gratitude!

Hi @gabemorris12, thanks for the kind words!

However, the only thing that is not implemented yet is a high-level function that lets you do it all in one command.  All low-level helper functions are already there! Example: mass-spring system with initial location `0` and initial velocity `a`:

```python
from sympy import *
s = symbols('s')
t, m, k, a = symbols('t, m, k, a', real=True)
x = Function('x')
X = Function('X')
diff_eq = m*diff(x(t), t, 2) + k*x(t)
print(diff_eq)
L = laplace_transform(diff_eq, t, s, noconds=True)
print(L)
L = laplace_correspondence(L, {x: X})
print(L)
L = laplace_initial_conds(L, t, {x: [0, a]})
print(L)
X_sol = solve(L, X(s))
print(X_sol)
x_sol = inverse_laplace_transform(X_sol[0], s, t)
print(x_sol)
```

This gives `a*sin(t*sqrt(k/m))*Heaviside(t)/sqrt(k/m)`, as it should.

So have fun with ODEs!

**Comment by gabemorris12** [comment]
Hi y'all! I've been playing around with some of the updated features here. It's all working great, but I do want to give some feedback on what I think would be a worthwhile feature. I'm not sure if this is the best place to ask, but it not then I can make a new issue.

When you take the laplace of a function, it will output the whole laplace expression like so:

```
>>> import sympy as sp                                                
>>> from sympy.abc import t, s
>>> x = sp.Function('x')(t)
>>> sp.laplace_transform(x.diff(), t, s)[0]
s*LaplaceTransform(x(t), t, s) - x(0)
```

For ODE's, there can be many instances of the laplace of x(t), which can make the output look messy. It would be wonderful if there can be away to pass in another (optional) function as an alias of the laplace of x(t) to mimic what would be done by hand. For instance, 

```
>>> import sympy as sp                                                
>>> from sympy.abc import t, s
>>> x = sp.Function('x')(t)
>>> X = sp.Function('X')
>>> sp.laplace_transform(x.diff(), t, s, alias=X)[0]
s*X(s) - x(0)
```

This is just a thought, and I apologize if this is not the place to bring this up. Thanks!
