### ISSUE TITLE
Releasing SymPy 1.12

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#24601]
This issue is to track the release of sympy 1.12. The release notes for 1.12 are here:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.12

The issue for the previous release 1.11 is #23740

The release branch for 1.12 will be created shortly.

The list of issues and PRs with the 1.12 milestone is here:
https://github.com/sympy/sympy/milestone/63

Todo:

- [ ] Clean up the release notes
  - [ ] Bring all deprecations and breaking changes up to the top.
  - [ ] Mention any highlights
  - [ ] Clear up wording of notes.
  - [ ] Aggregate similar notes?

- [x] Set up the release branch and versions:
  - [x] Open a PR to update the version on the master branch to 1.12.dev. #24774
  - [x] Create the release notes page for 1.13: https://github.com/sympy/sympy/wiki/Release-Notes-for-1.13
    - [x] Check that the supported Python versions for 1.12 are correct (versions are listed as 3.8-3.11, 3.7 is not yet EOL and 3.12 is not yet released.).
    - [x] Check if the supported Python versions for 1.13 should be changed (probably should add 3.12 prereleases to CI).
       - [x] Update changes in the release notes
       - [x] Update changes in CI and setup.py, benchmarks etc. #24776
  - [x] Open a PR for master to update the AUTHORS file. #24775
    - [x] Check if author names look correct and maybe contact some authors for clarification (shouldn't be necessary with the new mailmap changes).
  - [x] Create the branch
    - [x] Merge the updated AUTHORS file and then immediately...
    - [x] ... Create the 1.12 release branch and then immediately...
    - [x] ... Merge the master branch version update.
  - [x]  Fix the branches
    - [x] Make and merge a PR to change the version on the release branch to 1.12rc1 and also fix benchmarks for 1.12 branch. #24783
    - [x] Make and merge a PR to master to point the benchmarks previous release at the release branch and then also add any newer Python versions. #24776
    - [x] Update branch rules for `*.*` in GitHub settings.
    - [x] Update branch rules for master in GitHub settings.
  - [x] Announce release branch to mailing list

- [ ] Clean up release scripts
   - [ ] Keep release/README updated #23780.

- [ ] Resolve all issues and PRs with the 1.12 tag, backporting to the 1.12 branch if necessary.
  - [x] #24782 (backport gh-24789)

- [ ] Issue a release candidate
  - [ ] Make a tag `sympy-1.12rc1`.
  - [ ] Upload the release files to GitHub
  - [ ] Upload the release files to PyPI
  - [ ] Email announcement to the mailing list

- [ ] Wait to see if problems are reported with rc1. More RCs needed?

- [ ] Make a final release
  - [ ] Change version to 1.12 in `sympy/release.py`
  - [ ] Make a `sympy-1.12` tag
  - [ ] Upload the release files to GitHub
  - [ ] Upload the release files to PyPI
  - [ ] Update the docs website
    - [ ] Change versions.json
  - [ ] Make an announcement to the mailing list
  - [ ] Add SHA and Authors to the release notes

- [ ] Wait to see reports of regressions. Bugfix release needed?

**Comment by faze-geek** [comment]
Maybe irrelevant but I had compiled some issues which give expected results on master. Fixed but not closed yet. Kindly have a look and close them accordingly -
#17638
#14425
#14285
#12676
#8121

**Comment by oscarbenjamin** [comment]
> Maybe irrelevant

Yes, those are irrelevant. Please only use this issue to report anything that it actually related to the release like a bug that should be fixed before the release.

**Comment by sylee957** [comment]
I would like to set a milestone for #24590 because it attempts to complete some necessary deprecation that were attempted years ago

**Comment by asmeurer** [comment]
You mean specifically that we should deprecate order='old' before removing it? 

I don't think we should deprecate the actual ordering of classes. And the changes to the default sort order, if they end up being required, would be hard to deprecate.

**Comment by oscarbenjamin** [comment]
> I would like to set a milestone for #24590

That PR does not fix any urgent regression. It also does not bring any immediate improvement to users. It's part of an ongoing stalled piece of work that would eventually remove a metaclass but it doesn't actually remove that metaclass. I'm not sure that it brings any immediate benefit or that there is any value in shipping it out to users now rather than in a few months,

If the intention of the PR was to begin emitting a DeprecationWarning for something then I would agree that that is something that should be released as early as possible (if the deprecation/removal is actually needed).

I am not saying that it shouldn't be merged or that it should not be in the next release. It's just that I don't see any reason why a new release should in any situation be delayed just because that particular PR is unresolved. More importantly I don't think there is any reason that I should spend any time working on reviewing that PR as part of the release process.

I think it's easy to misunderstand what the milestones are really for. The purpose of the milestones is basically this:

1. Some things should be fixed by the next release particular where a new bug broke an existing workflow (i.e. if there is a regression since a previous release).
2. As part of the release process I (and anyone else who helps) will commit some time to fix these release blockers and the release will be delayed until that work is complete.

Concerning point 2 the reason I don't put out releases more often is simply that the amount of work involved in making a release always turns out to be more than anticipated.  Please only use milestones for things that really should be release blockers because otherwise it just adds to the work involved which discourages me from making more frequent releases.

There are many issues on the milestone that have been pushed back over several releases. I think that they are all important regressions which is why I haven't removed them from the milestone. The reason I haven't fixed them though is that fixing all of those as part of making a release is just too much work: we would never get a release out if I had to fix all of those first.

**Comment by oscarbenjamin** [comment]
> If we can completely remove BasicMeta and order='old' before the release then I say we should do it

Is there any benefit to removing this apart from improving future development efforts? Does it bring any immediate improvement for users?

If not then I would actually argue that this is the sort of changed that should be merged to master immediately after the release branch is made so that it can sit for as long as possible on master to get as much pre-release testing as possible.

Benefiting future development efforts is obviously worthwhile but there's no reason to rush a change like that into public release (in fact quite the opposite).

**Comment by asmeurer** [comment]
> If not then I would actually argue that this is the sort of changed that should be merged to master immediately after the release branch is made so that it can sit for as long as possible on master to get as much pre-release testing as possible.

Yes that sounds better actually. My main concern is that if we do manage to get it working, we should merge it sooner rather than later so it doesn't become stale. But that doesn't mean we need to rush it for the release. 

So let's see about deprecating order='old'. I don't think that should be hard. As far as I can tell, it's not used in library code. We can't deprecate the actual ordering of classes (that's as hard as removing it in the first place), but hopefully no one's implicitly depending on that. Some orderings of `args` might also change once we remove it (that's what makes it so hard), but there's no way to deprecate that.

**Comment by zouhairm** [comment]
any plans to produce a release candidate tag that folks (me included :p) can test with?

**Comment by oscarbenjamin** [comment]
There will be a release candidate

**Comment by jondo** [comment]
I See https://github.com/sympy/sympy/releases/tag/sympy-1.12. Why is this open?

**Comment by oscarbenjamin** [comment]
Good point!
