### ISSUE TITLE
Releasing SymPy 1.13

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#26169]
This issue is to track the release of SymPy 1.13. The release issue for SymPy 1.12 was at gh-24601.

The release notes for 1.13 are here:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.13

I will update the OP here with progress/todo.

Todo:

- [ ] Clean up the release notes
  - [ ] Bring all deprecations and breaking changes up to the top.
  - [ ] Mention any highlights
  - [ ] Clear up wording of notes.
  - [ ] Aggregate similar notes?

- [x] Set up the release branch and versions:
  - [x] Open a PR to update the version on the master branch to 1.13.dev. gh-26659
  - [x] Create the release notes page for 1.14: https://github.com/sympy/sympy/wiki/Release-Notes-for-1.14
    - [x] Check that the supported Python versions for 1.14 are correct
    - [x] Check that the supported Python versions for 1.13 are correct
  - [x] Open a PR for master to update the AUTHORS file. #26644
    - [x] Check if author names look correct and maybe contact some authors for clarification (shouldn't be necessary with the new mailmap changes). #26644
  - [x] Create the 1.13 branch
    - [x] Merge the updated AUTHORS file and then immediately...
    - [x] ... Create the 1.13 release branch and then immediately...
    - [x] ... Merge the master branch version update.
  - [x]  Fix the branches
    - [x] Make and merge a PR to change the version on the release branch to 1.13.0rc1 and also fix benchmarks for 1.13 branch gh-26660
    - [x] Make and merge a PR to master to point the benchmarks previous release at the release branch and then also add any newer Python versions. gh-26661
    - [x] Update branch protection rules for the release branch.
  - [x] Announce release branch to mailing list

- [ ] Clean up release scripts
   - [ ] Keep release/README updated #23780.

- [x] Resolve all issues and PRs with the 1.13 milestone, backporting to the 1.13 branch if necessary.
  - [x] gh-26319 (deferred)
  - [x] gh-24796 (deferred)
  - [x] gh-22237 (deferred)
  - [x] gh-19887 (deferred)
  - [x] gh-26221 (deferred)
  - [x] gh-26058
  - [x] gh-26318
  - [x] gh-26273

- [x] Issue a release candidate
  - [x] Push tag `sympy-1.13.0rc1` to trigger deploy to PyPI, GitHub release and docs repo.
  - [x] Email announcement to the mailing list

- [x] Wait to see if problems are reported with rc1. More RCs needed?

- [ ] Make a final release
  - [ ] Change version to 1.13 in `sympy/release.py`
  - [ ] Push tag `sympy-1.13.0rc1` to trigger deploy to PyPI, GitHub release and docs repo.
  - [ ] Make an announcement to the mailing list
  - [ ] Add SHA and Authors to the release notes

- [ ] Wait to see reports of regressions. Bugfix release needed?

**Comment by moorepants** [comment]
I see that the old milestone was added this. I switched it to the 1.13 milestone.

**Comment by oscarbenjamin** [comment]
We need a resolution to gh-26273.

The 1.12.1 release is ready to go at the push of a button and has the `mpmath < 1.4` dependency constraint just like 1.12.1rc1 which is already on PyPI. Once 1.12.1 is released we can release 1.13 but that also needs the `mpmath < 1.4` constraint.

I explained in gh-26273 and gh-26413 why we need this and concluded with  https://github.com/sympy/sympy/issues/26273#issuecomment-2028052195.

I am not putting out any releases without the version constraint and I also object to anyone else putting out any releases without the version constraint.

**Comment by moorepants** [comment]
I assumed that it was resolved when you released SymPy 1.12.1rc1 with these lines in setup.py:

```
         install_requires=[
              'mpmath >= 1.1.0, < 1.4.0',
          ],
```

I do disagree with adding the upper pin on mpmath, but it seemed you closed discussion by adding the pin and making the pre-release. I said in the thread that I have no more say and, thus, do not intend to (nor ever intended to) block adding it. I made my case for why we shouldn't add it but I don't see any actual resolution from rational argument because we both seem to have different core views on the development approach (reactive vs proactive). Secondly, you've done all the work in making the last many releases and your merit outweighs my opinion (at least that's how I see it). I do not see https://github.com/sympy/sympy/issues/26273 as a blocking issue from my perspective.

**Comment by oscarbenjamin** [comment]
Thanks Jason. I have released SymPy 1.12.1 with the fixes for CPython 3.12 and also NumPy 2.0 and some other things as well as the `mpmath < 1.4` cap.

We can now start the process of releasing 1.13.

**Comment by klmcwhirter** [comment]
Is there any remaining items left todo?

**Comment by oscarbenjamin** [comment]
I think everything is done now and we have had a few bugfix releases already.

Probably time to think about the next release soon.
