### ISSUE TITLE
Remove the function codomain() from file codomain.py

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9967]
the function "codomain" implemented in "codomain.py" is same as the functionality in "imageset" which is already implemented in SymPy.

What is to be done?
# TODO
- [ ] ~~Remove the file codomain.py from calculus part~~ . Remove the codomain() function from the codomain.py file.
- [ ] since it was there in Public API remove from __init__.py
- [ ] remove all tests of "only" codomain.py from tests/tests.codomain.py( tests of not_empty_in should not be removed)
- [ ] decide for the name of tests file for test_codomain.py

For seeing why this is happening see this [discussion](https://github.com/sympy/sympy/pull/9719#issuecomment-145685128) on PR #9719 .

**Comment by kevalds51** [comment]
Can I take this?

**Comment by gxyd** [comment]
Sure

**Comment by kevalds51** [comment]
The not_empty_in function is imported from the codomain.py module, so it wont work after we delete codomain.py in the first place. What should be done?

**Comment by gxyd** [comment]
First point was somewhat wrong, sorry for that. I have updated it. Have a look.

**Comment by VinaySingh035** [comment]
Has this issue been resolved, or can I try on this??

**Comment by gxyd** [comment]
There is already a PR #9975 for solving this issue, you can try some other issue.

**Comment by VinaySingh035** [comment]
ok thanks

**Comment by gxyd** [comment]
Fixed by #9975
